### ISSUE TITLE
[DX]: Sass のリファクタリング

### ISSUE THREAD

**Issue by TwoSquirrels** [uchikoshi-fes/uchikoshi-fes.jp-2022#77]
### 改善対象の事柄

- 同じ色をそれぞれ書いていて DRY でない

### 期待する挙動

- 定数として同じ色を使うことができる

### 補足情報

- [ ] 主要な色を Sass 変数で `/components/colors.scss` にまとめる
- [ ] ↑ を使う (`@use "相対パス" as *` のようにする)
- [ ] `/next-seo.config.js` からも読み取る

**Comment by gendaineko2222** [comment]
`pages/global.scss` に `:root` をおけばどこからでも `var(変数名)` で読み込めるからそっちのほうがシンプルかもです

例：

`pages/global.scss`
```scss
:root {
  --c-black: #000;
}
```
`〇〇.module.scss`
```scss
.title {
  color: var(--c-black);
}
```
